server:
  port: 9080
#  servlet:
#    context-path: /api

spring:
  kafka:
    template:
      default-topic: test
    producer:
      bootstrap-servers:
        - vip:9092
      retries: 0
      batch-size: 2MB
      properties:
        linger:
          ms: 2000
      buffer-memory: 5MB
    consumer:
      bootstrap-servers:
        - vip:9092
      key-serializer : class org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: test-consumers
